{% set version = "0.19" %}

package:
  name: libpciaccess
  version: "{{ version }}"

source:
  url: https://gitlab.freedesktop.org/xorg/lib/libpciaccess/-/archive/libpciaccess-{{ version }}/libpciaccess-libpciaccess-{{ version }}.tar.bz2
  sha256: a595ae61e57f4c3ddb26fbc89567212efbf477b43eda8500f36e00a259f03527

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage('libpciaccess', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - make        # [unix]
  host:
    - xorg-util-macros

test:
  commands:
    - test -f $PREFIX/lib/libpciaccess.so
    - test -f $PREFIX/lib/libpciaccess.so.0
    - test -f $PREFIX/lib/pkgconfig/pciaccess.pc
    - test -f $PREFIX/include/pciaccess.h

about:
  home: https://gitlab.freedesktop.org/xorg/lib/libpciaccess
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Generic PCI access library

extra:
  recipe-maintainers:
    - hmaarrfk
