{% set name = "libpciaccess" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/xorg/lib/{{ name }}/-/archive/{{ name }}-{{ version }}/{{ name }}-{{ name }}-{{ version }}.tar.bz2
  sha256: a29897dcbae7a653d5e429949f28822107987c5b958ebdb25b0628bf37a316ec

build:
  skip: True  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage('libpciaccess', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
    - pkg-config
  host:
    - xorg-util-macros

test:
  commands:
    - test -f $PREFIX/lib/libpciaccess.a
    - test -f $PREFIX/lib/libpciaccess.so
    - test -f $PREFIX/lib/libpciaccess.so.0
    - test -f $PREFIX/lib/pkgconfig/pciaccess.pc
    - test -f $PREFIX/include/pciaccess.h

about:
  home: https://gitlab.freedesktop.org/xorg/lib/libpciaccess
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Generic PCI access library'

extra:
  recipe-maintainers:
    - hmaarrfk
