travis:
  secure:
    BINSTAR_TOKEN: bf7GdcbPBow/4uYKeMOeyyfE96LBX11BOqnGeXeEmJGNxKmaeGvpcCZNrR1JW3jqVy+U7Zpz5pKb/YtnM3dSxUcqHxZHjSH+1a74r+ks5N2wpXg3ncFLCMeEQUt/kanmuC6iTVeZ81r44Y57EFxconCOMQ8JkuC4y8qjAdkrFm2ZLBdnltX41pt+9ycJoy2LKk08UPtTPQfrPd+GgJOUK3bAiPrDttZIoC5AhOtdWoC0uB3sxCZaH+iM4oR82NRfXAGoZayq3nF5dj8webxLi/DNXgoZabPij4S3ajZUuok7K7pBT76H2VVDbyahyskedDgnrzLK1NoFWuuJqrrUYQ83p78HJynXhvMvA99pkWOmmUZ/Hw1rJwOfEpuwePOC1hAHNj+MmpBg3QaxMB7sC271RY13oWIyrjBrPi/9V79RgKNrhycbpkaDApQPnydfWlfwYfs+YyP4a4qU6irjMMEurnuz+U5JTt2iDO0RnPjCKTAmLrWRgyRCtip6F3m9S8OjfIpCiMIOb05rXkVup5XnLHeKah3r6Nk6GtnEfBUmo0Uuax9be0IpJg8j8Vp9Cj76ofvqC+4OFB3EbUJXR0la87UMOOObqL9+vdO+KYqNXXQ1/D3MXwakZKEwtNZqlABsShO+LDtlWph9zYJrgG5RicPduRhxYmMDETJKHa0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
